### PR TITLE
Snapchat Module

### PR DESCRIPTION
**Pull request by AntikyLmao**
Good work Sitiaro, wish to work with you in the future :)

### CODE REVIEW

**Comment by AntikyLmao** [comment]
im new to this github thing so i just wanted to contribute to this amazing project so i had to research for 20 minutes on how to contribute to repos i hope i did it right

**Comment by Sitiaro** [comment]
You low-key messed some things up but it was a good attempt! Whenever you make a pull request, make sure to not delete any of the files that are present in the repo. If you want to make changes to one portion of the tool then do so without touching the other files. For ex, only edit/make changes to the files that are present in the snapchat folder instead of deleting the entire repository.

**Comment by AntikyLmao** [comment]
I have no clue what you just said, but i was just making it so that the snapchat part worked without all the starting stuff incase someone wanted to fork it into a replit. also good luck on your AI

**Comment by AntikyLmao** [comment]
@Sitiaro, hey are you still active? i have a project i want to introduce to you and hopefully we can partner up and get it done.

**Pull request closed without merging**
